export const CREATE_EVENT = 'create_event'
export const CREATE_TICKET = 'create_ticket'
export const CREATE_USER = 'create_user'
export const LOGIN_USER = 'login_user'
export const SAVE_EVENT = 'save_event'